mavlink-router/mavlink-router

comm.cpp, comm.h
This function will do a binary search to find the msg entry that is expense
better just get it once per message.
=> Just call mavlink_get_msg_entry() once per message

.gitignore, Makefile.am, TODO, tests/test.py
Script creates some endpoints, a mavlink-routerd process and sends
packets trough it. Currently, checking is minimal: checks if all
received packets have correct destinatary and expected quantity of them.
Naturally, tests can be improved on future, but it works as a initial
test demonstration. An issue that may be tackled is non-determinism
caused by the use of threads to each endpoint. Current small testcase
already makes use of `sleep()` to ensure order of packets, but that
may become unfeasible if test case grows. An obvious alternative would
be keeping tests small. But what about stress tests? Maybe more flexible
metrics are the solution then.
'test' target added, so one can issue `make test` to test - pymavlink
on Python path is a requirement.
=> tests: Small test script for routing

Makefile.am, README.md, TODO, conf.cpp, conf.h, main.cpp, mainloop.cpp, mainloop.h
Changes from v1:
- Accept `#` as a comment to Linuxfy a bit
- New `strcasecmp` macro to compare strings, ignoring case
- `null_check` macro is now `assert_or_return`.
- New patch adding possibility to have a dir in which .conf files can be put, allowing one to add and override previous configuration. Files on this dir are read in alphabetical order - allowing one to chain overrides.
-- This last patch involved some refactor - review it with care =D
=> Conf files - v2

main.cpp
Recent patches adding conf files end up allowing endpoints withou port
or baudrate. This patch should fix this and also add more checks to
ensure it won't happen again - soon, at least.
=> main: Ensure endpoints have all parameters properly set

conf.cpp, main.cpp
- main.cpp: opendir and strdup result were leaking on early returns
- main.cpp: # of files that can be parsed is limited - enforce limit
- conf.cpp: getline result was leaking on early return
=> Fix leaks on parse conf files code

Makefile.am, README.md, configure.ac
This way, mavlink-router is able to understand different MAVLink
messages definitions. To do so, one needs to inform the different
`common.xml` file via MAVLINK_XML option to configure:
$ ./configure MAVLINK_XML=path/to/common.xml
=> configure: allow different mavlink dialect to be used

README.md, main.cpp
- Instead of using `key-name`, prefer `KeyName`
- Updated README to reflect this
- Remove stray `Type` key on UdpEndpoint sample on README.
=> config files: Consistency on key names

ulog.cpp
I was able to reproduce the 'Invalid ULog Magic number' once
and it keep printing this message forever so better restart
the ULog.
=> ULog: Restart it when initial header have problems

main.cpp
Help instructions was saying that parameter to set configuration files
directory was --conf-dir, but code was using --dir-file. Using
--conf-dir now.
=> main: Declared parameter was different from parameter in help text

main.cpp
It was converting `--conf-file` to `-i`, instead of `-c`
=> main: Fix wrong argument expansion

logendpoint.cpp
auto parameters on lambda function declaration is a C++14 feature. Not
all environments support it, though.
=> log: Stop using C++14 feature

endpoint.cpp
They can be pretty common when no one is listening on one network.
Note, this is more of a temporary measure, a proper solution is coming.
=> debug-log: Not log 'Network unreachable' errors

README.md, mainloop.cpp
Missing addition of file descriptor to epoll. Fixed - now, every time
an endpoint is added to tcp endpoint list, it will automatically enroll
file descriptor on epoll.
Also, RetryTimeout property documented on README.
=> tcp endpoint: After reconnection, mavlink-router wasn't listening it

main.cpp, mainloop.h
When getting log dir from any conf file, mavlink-router was actually
not using it - it was being forgot on stack.
=> conf file: Fix log dir usage

endpoint.cpp, endpoint.h, mainloop.cpp, mainloop.h, pollable.h, timeout.cpp, timeout.h
First commit on this PR does the work, but uses `dynamic_cast`.
Second commit gets rid of `dynamic_cast`.
Kept them separated to ease review.
=> Fix high cpu

README.md, examples/config.sample
Added a example of a config file, with a header that explain in details
all configurations.
Readme changed to point to this file.
=> conf file: Explain all possible configurations

examples/config.sample, main.cpp
It was being inconsistently called LogDebugLevel.
=> config file: Name property about debug log level as DebugLogLevel

endpoint.cpp, mainloop.cpp
mavlink-router was not reporting stats of connected TCP endpoints.
Also, added endpoint filedescriptor on stats, as this helps identifiying
endpoints.
=> TCP Endpoints: Report stats

Makefile.am, autolog.cpp, autolog.h, examples/config.sample, main.cpp, mainloop.cpp, mainloop.h
This new MavlinkDialect option will identify flight stack MAVLink
dialect based on heartbeat.
This option is the new default, so people aren't expected to normally
deal with this setting.
=> log: Add `auto` dialect, that will guess autopilot MAVLink dialect

src/common/macro.h, src/mavlink-router/ulog.cpp
GCC 7 turned the fallthrough warning on by default. These are the ways
to turn them handle them on the cases it should fallthrough:
switch (cond) {
case 1:
bar (1);
__attribute__ ((fallthrough)); // C and C++03
case 2:
bar (2);
[[gnu::fallthrough]]; // C++11 and C++14
case 3:
bar (3);
[[fallthrough]]; // C++17 and above
/* ... */
}
More info: https://dzone.com/articles/implicit-fallthrough-in-gcc-7
And it does work with clang as well.
=> Use gnu++11 to handle fallthrough warning

src/mavlink-router/endpoint.cpp
If an endpoint is sending a packet through a channel and there are more
components IDs on the same endpoint, mavlink-router would send back any
message through the same channel.  It's never the expected behavior to
receive the message reflected back and there's no way to the other end
to deal with it. Exception would be of course check the destination
sysid/compid, but those may not be present.
This also changes the behavior if the same vehicle/component is
connected through multiple endpoints on mavlink-router, each of them
having more components. mavlink-router will now drop the packet do avoid
loops.
This is an alternative to the fix provided in
https://github.com/01org/mavlink-router/pull/113 and should fix the
issue in https://github.com/01org/mavlink-router/issues/107.
=> endpoint: don't send msg back to the same endpoint

examples/config.sample, src/common/conf_file.h, src/mavlink-router/autolog.cpp, src/mavlink-router/autolog.h, src/mavlink-router/binlog.cpp, src/mavlink-router/binlog.h, src/mavlink-router/logendpoint.cpp, src/mavlink-router/logendpoint.h, src/mavlink-router/main.cpp, src/mavlink-router/mainloop.cpp, src/mavlink-router/mainloop.h, src/mavlink-router/ulog.cpp, src/mavlink-router/ulog.h
This PR includes 2 changes:
- change the log file permissions to read-only after the file is closed. This can be used by other clients to detect when logging is finished
- add an option `LogMode` that can be set to `arm_until_disarm`. In that case logging is started when the vehicle is armed and stopped when disarmed. The default is `always`, which is the same behavior as before.
=> Logging: set file to read-only & add logging mode option

examples/config.sample, src/mavlink-router/main.cpp
We don't use underscores in config entries: a dash should rather be
used.
=> logging: use dash on config entry

src/mavlink-router/autolog.cpp, src/mavlink-router/binlog.cpp, src/mavlink-router/logendpoint.cpp, src/mavlink-router/logendpoint.h, src/mavlink-router/ulog.cpp
The expected system id for log streaming was hardcoded to 1, and thus
logging would not work when the autpilot is configured to have a different
sys id.
This patch changes the behavior to pick up the system id from the heartbeat
of the autopilot.
=> logging: allow autopilot logging from an arbitrary system id

src/mavlink-router/mainloop.cpp
epoll can fail for example when an UART FTDI cable is plugged out and the
associated device becomes invalid. In that case we remove the file
descriptor from the list.
We also quit mavlink-router, because in most cases the error is fatal,
and an external component (e.g. systemd) can restart it.
If this behavior is not desired by default, we can make it a config option.
The current behavior is that mavlink-router busy-loops in case the cable is plugged out.
=> mainloop: handle epoll_wait error

src/common/util.h
Following the Gentoo patch here: https://cgit.gentoo.org/proj/musl.git/tree/sys-libs/efivar/files/27-strndupa.patch?id=0d259ad72bb04c5a9bc1c83d3
This enables build on musl-based systems (e.g. Alpine Linux).
=> add support for musl

src/mavlink-router/endpoint.cpp, src/mavlink-router/endpoint.h, src/mavlink-router/main.cpp, src/mavlink-router/mainloop.cpp, src/mavlink-router/mainloop.h, src/mavlink-router/ulog.cpp
Add Filter field to endpoint configuration to limit the messages that are sent to particular endpoint and improve performance.
For example XYZ is interested only in messages 24,33,76,320,321,323.
This configuration filters all other messages so that they're not sent to XYZ and don't need to be parsed.
[UdpEndpoint XYZ]
Mode = Normal
Address = 127.0.0.1
Port = 14530
Filter = 24,33,76,320,321,323
=> Enable message filtering to reduce network traffic.

Makefile.am, src/mavlink-router/logendpoint.cpp, src/mavlink-router/logendpoint.h
With the default kernel settings (/proc/sys/vm/dirty_expire_centisecs = 3000), it is possible to lose up to 30s of logging data in events of power loss.
This patch reduces worst-case loss to 1s by calling fsync() every second.
=> LogEndpoint: call fsync() once per second

.travis.yml
lxml now needs python >= 3.5. Switch to Ubuntu Bionic for that.
=> Update travis to ubuntu bionic

Makefile.am, src/mavlink-router/logendpoint.cpp, src/mavlink-router/logendpoint.h
With the default kernel settings (/proc/sys/vm/dirty_expire_centisecs
= 3000), it is possible to lose up to 30s of logging data in events of
power loss.
This patch reduces worst-case loss to 1s by calling fsync() every second.
=> LogEndpoint: call aio_fsync() once per second

.clang-format, src/mavlink-router/endpoint.cpp, src/mavlink-router/endpoint.h, src/mavlink-router/logendpoint.cpp
UDP and TCP disabled MAVLink CRC checks because those protocols have
built-in CRC already. However there are several failure cases when relying
only on these:
- For the UDP case, if a UDP packet is not aligned with MAVLink messages,
UDP packet drops or reorderings lead to corrupt MAVLink messages.
For example some implementations fill up a fixed-size UDP packet.
- A connected component might just forward bytes that come from another
(lossy) link. In my case it was a shared memory implementation
translating to UDP, and the shared memory implementation
dropped/had corrupt bytes.
These cases can lead to corrupt log files and even busy-loops of mavlink
router within the log processing.
An alternative would be to just ensure CRC is checked in the log classes.
=> Enable MAVLink CRC checks on UDP/TCP

.gitignore, examples/config.sample, src/mavlink-router/autolog.cpp, src/mavlink-router/autolog.h, src/mavlink-router/binlog.h, src/mavlink-router/logendpoint.cpp, src/mavlink-router/logendpoint.h, src/mavlink-router/main.cpp, src/mavlink-router/mainloop.cpp, src/mavlink-router/mainloop.h, src/mavlink-router/ulog.h
Added two configuration options in the conf files: `MinFreeSpace` and `MaxLogFiles`. If there are less than `MinFreeSpace` bytes available on the device used for log storage, or if there are more than `MaxLogFiles` in the log directory, then files will be deleted. They are deleted in the order of their numerical index (the 5-digit number at the beginning of every log filename, before the timestamp), until both limits are met.
Both limits can be disabled by setting them to 0.
=> Automatic log deletion as storage space fills up

examples/receiver.py, examples/sender.py, src/mavlink-router/endpoint.cpp
This reverts commit 940f0b8caf3cf61879c3cdfebd66a78eb127bd70.
I think this was probably one artficact of putting the uart in raw mode
rather than sane mode. We don't care about RTS/DTR and none of the
flight stacks we support are setting those.
Fix #128, but needs testing
=> Revert "endpoint: set RTS/DTR state"

src/mavlink-router/logendpoint.cpp
Issue: every time we armed something was deleting all logs on the vehicle. It was then narrowed down to mavlink router since it's one of the only applications touching these logs.
Bug: change bytes_to_delete and files_to_delete from uint64_t to int64_t, otherwise it cannot get a negative value. These values become negative in these two lines I change when there is enough space, but they will be then seen as massive positive numbers due to the sign bit. This was difficult to find because the prints all use %ld, therefore in the print the number were negative.
FYI @bkueng @ItsTimmy
=> fix log rotation

src/mavlink-router/logendpoint.cpp
This issue was only happening on a armv7hf and not on aarch64 or amd64. Apparently the size() on this specific CPU returned a uint32_t which then caused the subtraction to overflow when the result was negative.
In this way the result of the subtraction was never negative and we were always deleting all the existing logs.
With this fix we first cast to be signed and then perform the subtraction
=> add cast when computing how many log files to delete (log rotation)

src/mavlink-router/endpoint.cpp
resolves issue #207
The comment in L. 344 is IMHO saying what it should do, but the if statement which follows becomes true also then the message has a target comp id > 0 and thus is not broadcasting. 
this PR corrects this.
I've tested this on the system described in the above issue, and it seems to exactly do what I would think it should do.
:)
=> Corrected MAVLink routing

src/mavlink-router/mainloop.cpp
r the number of polled events is changed if there is a readable event EPOLLIN 
Changed to a local temporary variable rd.
=> fix reuse of r loop variable for p->handle_read

configure.ac, src/mavlink-router/logendpoint.cpp
`aio_init()` is GNU-specific, and not compatible with musl. Is there a reason for having those lines (i.e. has it been proven that this is useful), or can they be removed?
They are all that's needed to be fixed to support musl again.
=> Remove GNU-specific aio_init() function for musl compatibility

examples/heartbeat-print-tcp.py
very tiny modification to the heartbeat-tcp.py example script:
it in addition prints the heartbeat message's source systemId and componentID. This makes it much easier to identify the source and see the routing in action.
:)
=> heartbeat-print-tcp.py example: print also source IDs

README.md, configure.ac, examples/config.sample, src/mavlink-router/endpoint.cpp, src/mavlink-router/endpoint.h, src/mavlink-router/main.cpp
This PR will enable the use of IPv6 addresses in all endpoints and the command line options. The support for IPv6 is enabled by default, but can be disabled during the project configuration with `--disable-ipv6` (just like the systemd support).
To be able to properly differentiate between IPv4 and IPv6 addresses, this PR will also add input validation for IP addresses. IPv6 addresses must always be enclosed in square brackets, like the usage in URLs. Otherwise the IP:Port notation can't be verified.
Because the config file does use two different keys for IP and port, the angled brackets are not needed technically. But using also them there makes the usage consistent throughout the application and will make the input validation and differentiation between IPv6 and IPv4 easier.
All unicast …
=> Enable IPv6 Addresses and add Input Validation for IPs

src/mavlink-router/logendpoint.cpp
system_status is not a good field to get the "armed" state from: the
flight stack may change the system_status if for example a failsafe
condition is hit.  Derive the "armed" check from the base_mode field
that has a flag exactly with this meaning.
Thanks to Dan Moss for finding the issue.
Fix #226.
=> log: use base_mode rather than system_status

src/mavlink-router/mainloop.cpp
This could happen if in the same ground of events in the mainloop we have and operation disarming the timer followed by a timer read. This is a corner case that can happen more often when using mavlink message coalescing since the timer is continuously used. When this issue occurs the entire mavlink router mainloop is hanging since the timer read is done in this loop.
Timer read where we would get stuck: https://github.com/mavlink-router/mavlink-router/blob/51c72ffdce5ffb9d3f07010cd00de9dca4f8af4c/src/mavlink-router/timeout.cpp#L34
=> Timeout timer - change to NONBLOCK otherwise we could hang in a timer read operation

configure.ac, src/mavlink-router/main.cpp, src/mavlink-router/mainloop.cpp, src/mavlink-router/mainloop.h, src/mavlink-router/mainloop_test.cpp
TCP connections are expected to be dynamic. Just like we accept new
connection on the fly, we should also gracefully accept disconnects.
This was the behavior before, but change when we decided to handle UART
disconnections as fatal in 7e7ea939c8d7 ("mainloop: handle epoll_wait error").
For UART, this should not be common as the OS is simply removing the
device under us due to physical disconnection. This restores the previous
behavior for TCP.
In a poll loop it's usual to handle the POLLERR before, but in this case
we leave it after the POLLIN/POLLOUT. Even if we have a POLLERR
we allow the read()/write() calls to be done, so to give the endpoint
the chance to set the `is_valid()` flag.
While at it, fix minor coding style on indentation.
Fix: #252
=> Do not exit on TCP disconnects

src/mavlink-router/endpoint.cpp
To reduce the latency introduced by TCP socket in real time systems it is recommended to disable aggregation on the transport level.
While aggregation is on the TCP endpoint Introduced latencies of up to 50 milliseconds to some of the mavlink message.
While aggregation is off the TCP endpoint Introduced latencies of 2-3 milliseconds consistently.
Further Reading:
https://en.wikipedia.org/wiki/Nagle%27s_algorithm
=> Disable Nagle Algorithm on TCP sockets to reduce transport latency

src/mavlink-router/binlog.cpp
An off by one error in the for loop for sending NACK's on the unseen seqno's cause us to send a NACK for the packet. Last acked was the packet we just sent an ACK for, so we don't want to then send a NACK out for it.
The other change this does is just swap to using the MAVLink enum's for ACK/NACK for code readability.
=> binlog: Do not ACK then NACK the same packet

examples/config.sample
The `TcpServerPort` does not match the default value mentioned in the documentation and the code.
=> DOCS: Fix default TCP port in the sample config

configure.ac
enable_ipv6 should be ipv6, or else we get a following error:
| --enable-ipv6 [unknown-configure-option]
Signed-off-by: Ming Liu <liu.ming50@gmail.com>
=> configure.ac: fix a typo

.github/workflows/main.yml, .gitmodules, Makefile.am, configure.ac
Generating the mavlink C library on the fly is good because it allows us
to experiment new changes while also change the source code. However
this benefit is not used much for mavlink-router - one of the reasons
because the messages are probably developed first with the flight stack
and GCS code.
One of the reasons to migrate out of generating the headers is that this
will make it easier to migrate to meson, as it is currently not
compatible with generating the mavlink header files.
=> Use pre-built mavlink library

.gitmodules
Otherwise it doensn't work for people without authenticating, or without
a ssh key.
Fix: #292
=> gitmodules: use https instead of ssh

README.md, meson.build
On a side note, the readme should said to install meson with pip on Ubuntu, as the latest release on 21.04 for meson is Version: 0.57.0+really0.56.2-0.1 . So that doesn't pass the meson version requirement.
=> build: set to buildoptimized by default like previously

meson.build
As discuss there : https://github.com/mavlink-router/mavlink-router/pull/297
=> Meson: lower meson version requirement to 0.55

.clang-format, .github/workflows/check-format.yml, src/binlog.cpp, src/binlog.h, src/common/dbg.h, src/common/log.cpp, src/common/log.h, src/common/macro.h, src/common/mavlink.h, src/common/util.c, src/common/util.h, src/common/xtermios.cpp, src/endpoint.cpp, src/endpoint.h, src/logendpoint.cpp, src/logendpoint.h, src/main.cpp, src/mainloop.cpp, src/mainloop.h, src/mainloop_test.cpp, src/timeout.cpp, src/timeout.h, src/ulog.cpp, src/ulog.h
This PR introduces a few new settings in the clang-format file, some of those need at least clang-format 9:
- AlignConsecutiveDeclarations, AlignConsecutiveAssignments, AlignConsecutiveMacros: Specify as already used in most of the files, **even though I would like to enable all of them**.
- IndentPPDirectives: Was used this way in some files, and not in others -> **TBD**
- FixNamespaceComments: Enabling this is always a good idea to keep things in sync.
Please add your comments, whether consecutive assignments and declarations should also be aligned and how to set the indentation of preprocessor directives (nested #ifdef).
```cpp
int foo = 5;
double foobar = 7;
int    foo    = 5;
double foobar = 7;
```
All files were formatted again with clang-format 13. Most of the changes do not result …
=> Run clang-format on everything, add new CI workflow to check

README.md
Some operating systems (or CI environments) don't have meson > 0.55.
Meson can be installed via ``pip install meson``, but can't be installed into the user directory (--user) as it causes errors/conflicts with ninja when ``sudo ninja -C build install`` is called.
=> Readme: Meson version clarifications

src/autolog.cpp, src/autolog.h, src/binlog.h, src/common/conf_file.cpp, src/common/conf_file.h, src/endpoint.cpp, src/endpoint.h, src/logendpoint.cpp, src/logendpoint.h, src/main.cpp, src/mainloop.cpp, src/mainloop.h, src/ulog.h
The configuration of mavlink-router has to be merged from config file(s) and CLI options. Previously the config file was parsed to one set of structs, passed to a function as a set of parameters (instead of the full struct), which converted the options to another config structure collecting a list of endpoints, which was finally used to actually create the endpoints. I think having two config structs is quite confusing and overly complicated.
This PR reworks the internal flow of the configuration parameters to be like this:
- Parse config file(s) and CLI options to one struct per endpoint type (UDP, TCP, UART and Log)
- Have a single config struct with the full, merged configuration (global options + one list of endpoints per type), which is properly owned by the main function instead of …
=> Rework the internal flow of the config options

src/logendpoint.cpp, src/main.cpp
We changed the storage type from char* to std::string bug failed to
update the configfile and arg parse.
Fix: #309
=> logendpoint: fix not not parsing config file correctly

examples/heartbeat-print.cpp, src/autolog.cpp, src/binlog.cpp, src/comm.h, src/endpoint.cpp, src/endpoint.h, src/logendpoint.cpp, src/logendpoint.h, src/mainloop.cpp, src/mainloop.h, src/ulog.cpp
The parsing of mavlink header was intended to be contained in a single function, when we are reading the message from the associated buffer. Due to the addition of logging a long time ago and continuous use of the header fields to properly route the packets to the appropriate endpoint we ended up adding the same parsing to the log endpoints, including the check for different struct on mavlink1 vs mavlink2 wire format.
This is a cleanup aiming to stop doing that and rather just adding the appropriate fields in `struct buffer`. This also makes it much closer to be able to implement #39 since now we keep the msgid and could check for it against a set of msg ids in the correspondent `accept_msg()`.
This still needs to go through proper test and bench test, but apparently it's working (hey, it …
=> Cleanup mavlink header parsing

src/mainloop.cpp, src/mainloop.h, src/mainloop_test.cpp
When we exit mavlink-router we call logger->stop() to stop
and properly finalize the flight stack log. However this
call may want to send something to the flight stack to stop
sending the log.
We don't care about that call as if we are really stopping the flight
stack should detect the other side died/disconnected after a timeout.
Instead of marking the mainloop as not initiliazed upon signal,
serialize it with the other shutdown task in the main loop.
This fixes the crash:
Logging target system_id=1 on 00001-2021-12-29_23-57-32.bin
mavlink-routerd: ../src/mainloop.h:77: static Mainloop&Mainloop::get_instance(): Assertion `_initialized' failed.
Aborted
=> Fix assert crash when stopping log

.github/workflows/main.yml, meson-cross-i686.ini, tools/meson-i686-ubuntu-pkg-config, tools/meson-native-ubuntu-pkg-config
In general I think -Werror can't be the default due to different
compilers being used. However, for CI it's good to enable it because we
control the exact version we are using.
Enable -Werror to avoid introducing warnings.
=> ci: enable Werror

src/logendpoint.cpp
This prevents error on launch if the directory doesn't exist yet.
mavlink-router version v2-147-g02bc8b3+
Opened TCP Client [4]to_SITL: 127.0.0.1:5762
[Log Deletion] Error when measuring free disk space: No such file or
directory
Logging target system_id=1 on 00000-2021-12-29_20-26-46.bin
Simply ignore the error if errno == ENOENT: we don't need to cleanup
anything if the directory doesn't even exist.
This is an alternative minimal fix to the proposed in #317 by Pierre
Kancir.
=> Fix wrong error message about disk space

README.md, examples/config.sample, src/common/conf_file.cpp, src/common/conf_file.h, src/endpoint.cpp, src/endpoint.h
For a quite special use case, we'll need to filter outgoing messages by source component ID. This commit adds a corresponding config parameter to all endpoints. While implementing this feature, I also realized, that the current message ID filter is only present at the UDP endpoint. To keep everything consistent, I added the message ID filter to all endpoint types.
Our use case is the following:
Multiple telemetry receivers would be distributed on the ground and one or multiple drones fly in the coverage area. All of these receivers should forward the received messages to a central instance of mavlink-router. But transmission from the central router to the base stations should also work. All of them should send out the message, because it is not known which base station can reach the …
=> Add possibility to filter by source component ID

README.md
These guidelines were adapted from https://github.com/rostedt/libccli.
For people like me who generally work in the Linux kernel, it's hard to
apply some practices common to other projects. This is not as strict as
rules to contribute to Linux kernel, but at least give a hint on how
to make it easier for the PR to be reviewed and applied.
=> README: Write down some guidelines

src/mainloop.cpp, src/mainloop.h
When we run the destructor of the endpoints we will alread have deleted
all the timeouts. The idea of cleaning up the timeouts inside the
mainloop is just because we don't want to leak anything. However each
component should clean up after itself.
This fix the following valgrind trace:
== Invalid write of size 1
==374140==    at 0x113F1A: UdpEndpoint::~UdpEndpoint() (endpoint.cpp:913)
==374140==    by 0x4ECCC9F: ???
==374140==    by 0x131C1E: _M_release (shared_ptr_base.h:168)
==374140==    by 0x131C1E: ~__shared_count (shared_ptr_base.h:702)
==374140==    by 0x131C1E: ~__shared_ptr (shared_ptr_base.h:1149)
==374140==    by 0x131C1E: ~shared_ptr (shared_ptr.h:122)
==374140==    by 0x131C1E: _Destroy<std::shared_ptr<Endpoint> > (stl_construct.h:140)
==374140==    by 0x131C1E: …
=> mainloop: Fix UdpEndpoint destructor double free

src/endpoint.cpp, src/endpoint.h
Just a small fix of the error messages to be less confusing. Otherwise you'll get "Trying to write invalid fd" on a TcpEndpoint which was connected once, but then lost it's socket connection.
Steps to reproduce:
1. Add a TcpEndpoint to the config (e.g. to another mavlink-router) and a connection to a FMU (to generate telemetry data)
2. Start mavlink-router while the server to connect to is also started
3. Stop the server
4. See many "Trying to write invalid fd" errors until the server is started again
I suppressed the error message in `TcpEndpoint::write_msg()` first, but then thought, that rejecting the message in `Endpoint::accept_msg()` is actually nicer even though it introduces a very special condition to the previously generic `accept_msg` method.
=> TCP endpoint: Reject message when not connected

.github/workflows/main.yml
Currently only the result of the alpine linux 64 bit build is uploaded as a build artifact, in action runs as well as releases. Especially for the releases, I think we should provide the cross-compiled builds as well.  
(Unfortunately it doesn't solve cross-compiling for my board since my yocto linux glibc is too old. But I'm not sure, if we want to support legacy systems as well.)
This PR also fixes an issue with the version number that's automatically included in the build and displayed in the log messages during startup. Since the git tags are used for this version number, a shallow clone as it's done by default just gets us the commit hash and no "nice" version number.
=> CI: Upload cross-compiled artifacts as well

README.md, examples/config.sample, src/dedup.cpp, src/dedup.h, src/endpoint.cpp, src/endpoint.h, src/main.cpp, src/mainloop.cpp, src/mainloop.h, src/meson.build
As discussed in #240, parallel data links have some special needs. One of which is de-duplication of incoming messages.
This implementation has been used for some time and works just fine. I just needed to make some changes to make it compatible with the latest master, squashed some of Julian's commits and added some comments on the behavior.
=> Add optional message de-duplication

README.md, examples/config.sample, examples/heartbeat-print.cpp, src/endpoint.cpp, src/endpoint.h, src/main.cpp, src/mainloop.cpp, src/mainloop.h
Hello Maintainer of mavlink-router!
I added a sniffer function to mavllink-router.
The user can choose a Mavlink system-id that all messages are forwarded to. This is useful for real time debugging. One can choose his favorite mavlink inspector (Missionplanner and QGroundcontrol have nice ones...) and observe all Mavlink traffic.
You can leave this option on permanently with sys-id=254 for example, and whenever you wand to see what's going on just change you GCS id to 254 or connect with another GCS with this id.
I found this useful, so I added command line and configuration file functionality, so everyone can use it. 
Remark: Even on sniffer endpoint filters apply and messages are not echoed back.
Cheers,
-Guy
=> Sniffer function added

README.md, examples/config.sample, src/endpoint.cpp, src/endpoint.h, src/mainloop.cpp
When using multiple parallel (redundant) data links between two mavlink-router
instances, the loop prevention logic will effectively disable all but one of the
parallel links. This can be solved by having the endpoints of parallel link use
the same list of connected systems.
Rebased version of #330
=> Support redundant data links: Endpoint groups

src/endpoint.cpp
When a TCP endpoint detects an error, it schedules a reconnect (if not disabled). During the reconnection, the fd is invalid, but the endpoint still exists, so the write_msg() method is still called. But write_msg gives an error when the fd is invalid, even though this is expected as long as the reconnect attempts are running.
=> TCP endpoint: Fix invalid write errors during reconnect

src/mainloop.cpp
As requested in #347.
Since IPv6 support can't be disabled any more via the build system, it's no issue to just bind on the IPv6 socket (which listens on the IPv4 port as well).
=> TCP server: Bind to IPv6 socket as well

README.md, examples/config.sample, src/endpoint.cpp, src/endpoint.h, src/endpoints_test.cpp
We already have message filters on the outgoing side of an endpoint. This PR adds the same set of filters to the receiving side e.g. to limit the interaction abilities of some ground station software as requested in #345.
=> Complete the set of message filters: SysID filter and filtering incoming data

src/endpoint.cpp
Copy-paste error when initializing the input filtering from the config structs.
closes #368
=> Filtering: Fix AllowSrcSysIn

src/mainloop.cpp
Fixes the order of setting the sniffer system ID and logging it. Before, it always printed `An endpoint with sysid 0 on it will sniff all messages`
=> Log sniffer system ID after setting it

meson.build
[get_pkgconfig_variable](https://mesonbuild.com/Reference-manual_returned_dep.html#depget_pkgconfig_variable) => [get_variable](https://mesonbuild.com/Reference-manual_returned_dep.html#depget_variable)
=> Replace deprecated get_pkgconfig_variable

README.md
The readme gives the wrong names for the configuration file environment variables. They are prefixed with `MAVLINK_ROUTERD_` not `MAVLINK_ROUTER_`.
=> Fix environment variable documentation

.github/workflows/main.yml
Somehow the i686 build of the CI has failed recently as the build system selected the 64 bit version of libgtest instead of 32 bit.
This can be fixed by only installing the i368 version of libgtest-dev and not also the native one.
fixes #399.
=> CI: Fix issues with i686

src/endpoint.cpp, src/endpoint.h
This fixes the issue exhibited in #213. I have tested this on a Jetson TX2 and confirmed that by not performing the reset, the UART port is still accessible with minicom after shutting down mavlink router. For what its worth, setting stty's sane on the UART does not cause the same problem, so there is evidently some difference between the `reset_uart`  and stty sane despite the comment in the code. 
I hate to be the guy who offers a solution that's just "delete this code and it works", but its not clear to me what the underlying issue is and this does fix the bug.  I would totally understand if you all don't feel comfortable merging something like this, but I figured it might be helpful to throw this out there just in case. 
Would like to hear thoughts from the maintainers: Is there a …
=> Don't perform UART reset on shutdown

examples/config.sample, mavlink-router.service.in, src/common/log.cpp, src/common/log.h, src/endpoint.cpp, src/main.cpp, src/mainloop.cpp, src/mainloop.h
This adds a TRACE log level and changes the frequently output `log_debug`s to `log_trace`, so `debug` output can be enabled without flooding the output.
Additionally, log output can be redirected to syslog via `--syslog` CLI flag. By default, stderr is used.
=> Add TRACE log level and syslog output option
