- README.md
- comm.cpp
- examples/arm.py
- examples/receiver.py
- examples/sender.py
- main.cpp
- tools/checkpython
Maybe `checkpython` deserves its own PR - but others fix minor left overs.
> Assorted fixes

- README.md
- endpoint.cpp
- endpoint.h
- main.cpp
- mainloop.cpp
- mainloop.h
> Tcp client endpoint

- endpoint.cpp
- endpoint.h
- main.cpp
- mainloop.cpp
- mainloop.h
- timeout.cpp
- timeout.h
> Tcp reconnect

- Makefile.am
- README.md
- binlog.cpp
- binlog.h
- configure.ac
- main.cpp
- mainloop.cpp
- mainloop.h
- No more need to rebuild when changing Fligth Stack: for now, a config option `MavlinkDialect` is on
> Ardupilot log v5

- logendpoint.cpp
- logendpoint.h
- util.c
- util.h
> log: Create log directory if it doesn't exist

- endpoint.cpp
mavlink2 messages may be trimmed - i.e., any trailing 0 byte is
discarded. However, mavlink-router wasn't taking that into consideration
when getting target_system from a message: it was reading past message
length.
This patch just assumes broadcast if target_system offset is past
message length: it was zero anyway.
> routing: Fix lots of 'message to uknown sysid' errors

- xtermios.cpp
When resetting the tty instead of putting it in "raw" mode use "sane" mode
(see stty(1)) and also reset special characters to their defaults
(termios(3)).
> Fix uart reset

- main.cpp
Command line options should have preference over config files, as they
enable quick testing, for instance.
Work has been done on some relevant 'General' options that can be
overriden via command line options, like log verbosity and stats
reporting.
> conf files: Preference to command line options

- examples/config.sample
- src/mavlink-router/endpoint.cpp
- src/mavlink-router/endpoint.h
- src/mavlink-router/main.cpp
- src/mavlink-router/mainloop.cpp
- src/mavlink-router/mainloop.h
Fix #89 
@mhkabir can you give this a try?  I tested on a pixhawk and seems to be working fine.  You need to set `FlowControl = true`  in the config file
> Add support for HW flow control

- examples/px4-offboard-mode.cpp
This is a more complete example, doing takeoff, moving arround and landing.
**Only tested in simulator yet**
> samples: Improve px4-offboard-mode

- .gitignore
- Makefile.am
- examples/arm-authorizer.cpp
> examples: Add a simple example of a arm authorizer

- examples/px4-offboard-mode.cpp
This was tested in a real drone and works fine.
> Improvements in px4-offboard-mode sample

- .travis.yml
- Makefile.am
Given that Python 2's end-of-life is approaching, I've transitioned the Python calls to Python 3
> Build: Now using Python 3

- src/mavlink-router/endpoint.cpp
This pr fixes the latency on the serial port that is only noticeable when communicating at high speeds.
> reducing poll latency with ioctl serial control

- examples/heartbeat-print-tcp.py
- examples/heartbeat-print.py
- tests/routing_test.py
This came up in Python 3 testing in:
https://github.com/julianoes/PX4-Python-tests/
https://travis-ci.org/julianoes/PX4-Python-tests/jobs/637867694
> Fixed trivial Python issues reported by flake

- src/mavlink-router/endpoint.cpp
- src/mavlink-router/mainloop.cpp
PR  #209 squashed into one commit
didn't know how to do the squash properly, so just created new PR and closed old
sorry
> Streamline some log outputs #2

- .github/workflows/main.yml
Allow easy access of the binaries for development, test and also for official releases
> github actions: Add artifacts and release binaries 

- .github/workflows/main.yml
This commit adds support for building a .deb archive for installation on Debian-derived systems.
> Add .deb package build to Github Actions

- README.md
Add some common distros: Debian, Ubuntu, Fedora and Archlinux.
> README: expand package list for other distros

- .github/workflows/main.yml
workaround dockcross so we install additional dependencies inside the
container.
> ci: install additional deps

- .github/workflows/main.yml
- README.md
- examples/arm.py
- examples/heartbeat-print-tcp.py
- examples/heartbeat-print.py
- examples/heartbeat-sender.py
- examples/receiver.py
- examples/sender.py
- tests/routing_test.py
- tools/git-clang-format
I had to clean up some code first before fixing things.
The routing test script was failing because the the sender was targeting component 1, but the response was sent by component 0. It would have worked the other way around, though (because of the component broadcast rule). But this also didn't work before, because the source component ID was not set in the `mavutil.mavlink_connection()`.
For easier modification and less magic constants, I introduced a variable to set the number of sent messages as well.
> Update/ patch python scripts for python 3, fix routing test script

- .clang-tidy
- .github/workflows/main.yml
- README.md
- clangtidy-checks.md
- examples/arm-authorizer.cpp
- examples/heartbeat-print.cpp
- examples/px4-offboard-mode.cpp
- meson.build
- src/autolog.cpp
- src/autolog.h
- src/binlog.cpp
- src/binlog.h
- src/common/conf_file.cpp
- src/common/conf_file.h
- src/common/log.cpp
- src/common/util.cpp
- src/common/util.h
- src/endpoint.cpp
- src/endpoint.h
- src/logendpoint.cpp
- src/logendpoint.h
- src/main.cpp
- src/mainloop.cpp
- src/mainloop.h
- src/pollable.cpp
- src/timeout.cpp
- src/ulog.cpp
- src/ulog.h
- tools/meson-clang-tidy.sh
Based on #304, but already posted to show what I'm working on. Just ignore the first three commits.
To improve code quality, I let clang-tidy fix some things I consider a bad or error prone coding style. The checks were hand-picked and all changed reviewed manually before committing. For easier review, I created one commit per clang-tidy rule, but I would suggest squashing them before merging (when the other contributors are happy with the changes).
I also realized, that the unit test aren't run on the CI, so I snug a fix into this PR.
> Modernize code and enable unit test in CI again

- .clang-format
- examples/arm-authorizer.cpp
- examples/px4-offboard-mode.cpp
- src/binlog.cpp
- src/common/conf_file.cpp
- src/endpoint.cpp
- src/logendpoint.cpp
- src/main.cpp
- src/mainloop.cpp
- src/ulog.cpp
A few formatting and struggled with while doing some refactors in #143. First commits are actually from that PR and can be ignored here, I'm only including them because otherwise we would have some needless conflicts.
> Tweak clang-format

- examples/config.sample
- src/logendpoint.cpp
- src/logendpoint.h
this is mandatory for multi fcu configuration to select the right one to log
> Allow to set fcuid to log explicitly

- src/endpoint.cpp
- src/endpoint.h
- src/mainloop.cpp
- src/mainloop.h
More details on last commit message and on !10.
Fix: #110
> UdpClient: switch back to broadcast on inactivity

- README.md
- examples/config.sample
Extract commit changing the docs from #305 so it can already be applied while others are reworked.
> Docs: Integrate detailed description of the routing behaviour

- src/endpoint.cpp
Extracted from unit test commit in #305
> Fix has_sys_id()

- .github/workflows/check-format.yml
- .github/workflows/main.yml
Update package database before trying to install.
> ci: Add misssing update
